@todoistApiKey=<KEY>
@taskId=<TASK ID>

### Stats call
GET https://api.todoist.com/api/v1/tasks/completed/stats
Authorization: Bearer {{todoistApiKey}}
Content-type: application/json

### Sync call
POST https://api.todoist.com/api/v1/sync
Authorization: Bearer {{todoistApiKey}}
Content-type: application/json

{
    "sync_token": "*",
    "resource_types": "[\"filters\"]"
}

### Tasks call
GET https://api.todoist.com/api/v1/tasks?limit=200
Authorization: Bearer {{todoistApiKey}}
Content-type: application/json

### Filter call - today
GET https://api.todoist.com/api/v1/tasks/filter?query=today&limit=200
Authorization: Bearer {{todoistApiKey}}

### Filter call - overdue
GET https://api.todoist.com/api/v1/tasks/filter?query=overdue&limit=200
Authorization: Bearer {{todoistApiKey}}

### Filter call - tomorrow
GET https://api.todoist.com/api/v1/tasks/filter?query=tomorrow&limit=200
Authorization: Bearer {{todoistApiKey}}

### Update a single task to tomorrow
POST https://api.todoist.com/api/v1/tasks/{{taskId}}
Authorization: Bearer {{todoistApiKey}}
Content-Type:  application/json

{
    "due_date":"2025-07-27",
    "due_string":"19 Jan",
    "due_lang": "en"
}

### Update the daily goal
POST https://api.todoist.com/api/v1/sync
Authorization: Bearer {{todoistApiKey}}
Content-Type:  application/json

{
    "commands": [
        {
        "type": "update_goals",
        "uuid": "b9bbeaf8-9db6-452a-a843-a192f1542893",
        "args": {"daily_goal": 16}
    }
    ]
}

